modLoader = "javafml"
loaderVersion = "${loaderVersion}"
license = "CC-BY-NC-SA-4.0"
issueTrackerURL = "https://github.com/evanbones/redelight-map/issues"

[[mods]]
modId = "redelightmap"
version = "${version}"
displayName = "Redelight-map"
authors = "evanbones"
description = '''
Fork of Delight-(down)map by ConfiG to fix mod incompatibilities.
'''
credits = "Enchanted_Games for making Delight-map. ConfiG for making Delight-(down)map."
logoFile = "assets/icon.png"
displayURL = "https://modrinth.com/mod/redelight-map"

[[dependencies.redelightmap]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.redelightmap]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "redelightmap.mixins.json"

#? if >=1.20.1 {
[[dependencies.redelightmap]]
modId = "yet_another_config_lib_v3"
mandatory = false
versionRange = "[0,)"
side = "CLIENT"
#? }
