[versions]
mixinextras = "0.5.5"

[libraries]
mixinextras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }

[plugins]
jsonlang = { id = "dev.kikugie.postprocess.jsonlang", version = "2.1-beta.4" }
modpublish = { id = "me.modmuss50.mod-publish-plugin", version = "1.1.0" }

fabric-loom = { id = "fabric-loom", version = "1.13-SNAPSHOT" }
neoforge-moddev = { id = "net.neoforged.moddev", version = "2.0.134" }
neoforge-moddev-legacyforge = { id = "net.neoforged.moddev.legacyforge", version = "2.0.134" }
